//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthenLightHosp
{
    using System;
    using System.Collections.Generic;
    
    public partial class assurance
    {
        public int id { get; set; }
        public int no_police { get; set; }
        public string nom_societe_assurance { get; set; }
        public int id_client { get; set; }
    
        public virtual patient patient { get; set; }
    }
}
