//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthenLightHosp
{
    using System;
    using System.Collections.Generic;
    
    public partial class dossier_admission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dossier_admission()
        {
            this.accomodation_sejour = new HashSet<accomodation_sejour>();
        }
    
        public int id { get; set; }
        public int id_client { get; set; }
        public System.DateTime date_admission { get; set; }
        public Nullable<System.DateTime> date_conge { get; set; }
        public string raison_admission { get; set; }
        public int id_lit { get; set; }
        public int id_medecin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<accomodation_sejour> accomodation_sejour { get; set; }
        public virtual patient patient { get; set; }
        public virtual lit lit { get; set; }
        public virtual employe employe { get; set; }
    }
}
