//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthenLightHosp
{
    using System;
    using System.Collections.Generic;
    
    public partial class lit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lit()
        {
            this.dossier_admission = new HashSet<dossier_admission>();
        }
    
        public int id { get; set; }
        public int id_departement { get; set; }
        public int id_accomodation { get; set; }
        public bool occupe { get; set; }
    
        public virtual accomodation accomodation { get; set; }
        public virtual departement departement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dossier_admission> dossier_admission { get; set; }
        public virtual lit lit1 { get; set; }
        public virtual lit lit2 { get; set; }
    }
}
