//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthenLightHosp
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_lits_informations
    {
        public string departement { get; set; }
        public string type { get; set; }
        public int id { get; set; }
        public int id_departement { get; set; }
        public int id_accomodation { get; set; }
        public bool occupe { get; set; }
    }
}
