//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthenLightHosp
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_dossier_nom_prenom
    {
        public string nom { get; set; }
        public string prenom { get; set; }
        public int id { get; set; }
        public int id_client { get; set; }
        public System.DateTime date_admission { get; set; }
        public Nullable<System.DateTime> date_conge { get; set; }
        public string raison_admission { get; set; }
        public int id_lit { get; set; }
        public int id_medecin { get; set; }
    }
}
